### PR TITLE
getAsStruct: Filter members to fields only

### LINKED ISSUE #32: When converting a lua table into a struct - ensure that we ignore anything that isn't a field member in the struct

### PR DESCRIPTION
**Pull request by ArthaTi**
Closes #32

### CODE REVIEW

**Comment by BradleyChatha** [comment]
Nice, cheers for that.

Would you mind writing up a quick unittest for this fix? If not then I can do it at some point :)

**Comment by ArthaTi** [comment]
Sure enough, I'll try to make one whenever I can.

**Comment by ArthaTi** [comment]
There we go. I think it might be a good idea to add more unittests for this. I've also encountered issues with delegates; I think the context passed to delegates gets broken, and documentation only seems to cover context-less delegates, but that probably deserves its own issue. 

It might be relevant, so I've recently learnt of mir.ion, maybe it could be possible to integrate it to handle metaprogramming and attributes automatically.

**Comment by BradleyChatha** [comment]
Nice, thanks for that.

Yeah, generally I accept that this library is poorly tested but I find I've found it really hard this year to motivate myself to do much with/in D.

The delegate stuff is super jank as you've noticed, definitely requires a bit more looking into (however, due to what I mentioned above, it's probably gonna be like this for a while :/ )

`mir.ion` is really cool. I do wonder if it's appropriate to integrate directly with it in this library or not though. Could definitely add it as an optional feature though via a `version(XXX)` guard.

Either way, this MR looks good to go, I'll get it merged and tagged so it can start being used in dub ASAP.

**Pull request merged**
